name: traefik-playground

services:
  traefik-playground:
    image: jspdown/traefik-playground:${RELEASE_VERSION:-latest}
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command:
      - --addr=:8080
      - --secret-key=secret
      - --tester-timeout=2s
      - --max-processes=50
      - --db=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432?sslmode=disable
    networks:
      - postgres

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
