name: Release

# This workflow is invoked when a new tag is created.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml

  publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Extract the name of tag from the GITHUB_REF.
      - name: Set RELEASE_VERSION env variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # Build the Docker image.
      - name: Build image
        run: nix develop --command make build-image-${RELEASE_VERSION}
      # Push the image on the Docker Hub registry.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/traefik-playground:${{ env.RELEASE_VERSION }}

